card_manage/cards/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'cards'


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.view_info, name='view_info'),
    path('add_card/', views.add_card, name='add_card'),
    path('edit_card/<int:id>/', views.edit_card, name='edit_card'),
    path('delete_card/<int:id>/', views.delete_card, name='delete_card'),
    path('search_card/', csrf_exempt(views.search_card), name='search_card'),
]

card_manage/cart_manage/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cards.urls', namespace='cards')),
]

card_manage/cards/models.py
from django.db import models


class Cards(models.Model):

    STATUS = [
     ('ACTIVATED', 'ACTIVATED'),
     ('NOT ACTIVATED', 'NOT ACTIVATED'),
     ('EXPIRED', 'EXPIRED'),
    ]

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    card_series = models.PositiveIntegerField()
    number_card = models.CharField(max_length=16)
    amount = models.DecimalField(max_digits=4, decimal_places=2)
    data_created = models.DateTimeField(auto_now_add=True)
    data_end = models.DateTimeField()
    status = models.CharField(choices=STATUS, default='ACTIVATED', max_length=100)

    def __str__(self):
        return f'Серия Карты {self.card_series}: {self.first_name} {self.last_name}'

card_manage/cards/forms.py
from django import forms

from .models import Cards


class DateInput(forms.DateInput):
    input_type = 'date'


class CardForm(forms.ModelForm):

    class Meta:
        model = Cards
        fields = '__all__'
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'card_series': 'Серия карты',
            'number_card': 'Номер карты',
            'amount': 'Сумма',
            'data_end': 'Дата окончания',
            'status': 'Статус карты'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'card_series': forms.NumberInput(attrs={'class': 'form-control'}),
            'number_card': forms.NumberInput(attrs={'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'data_end': DateInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'})
        }

card_manage/cards/views.py
import json

from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse

from .forms import CardForm
from .models import Cards


def search_card(request):
    """Поисковик на главной странице"""
    if request.method == 'POST':
        search_str = json.loads(request.body).get('searchText')

        cards = Cards.objects.filter(
            first_name__icontains=search_str) | Cards.objects.filter(
            last_name__icontains=search_str) | Cards.objects.filter(
            card_series__istartswith=search_str) | Cards.objects.filter(
            number_card__istartswith=search_str) | Cards.objects.filter(
            amount__istartswith=search_str) | Cards.objects.filter(
            data_created__istartswith=search_str) | Cards.objects.filter(
            data_end__istartswith=search_str) | Cards.objects.filter(
            status__icontains=search_str)

        data = cards.values()
        return JsonResponse(list(data), safe=False)


def index(request):
    """Главная страница"""
    cards = Cards.objects.all()
    paginator = Paginator(cards, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'cards': cards, 'page_obj': page_obj}
    return render(request, 'cards/index.html', context)


def view_info(request, id):
    """Информация об объекте"""
    return HttpResponseRedirect(reverse('cards:index'))


def edit_card(request, id):
    """Редактирование объекта"""
    if request.method == 'POST':
        card = Cards.objects.get(pk=id)
        form = CardForm(request.POST, instance=card)
        if form.is_valid():
            form.save()
            return render(request, 'cards/edit_card.html', {
                'form': form,
                'success': True})
    else:
        card = Cards.objects.get(pk=id)
        form = CardForm(instance=card)
    return render(request, 'cards/edit_card.html', {
                'form': form})


def delete_card(request, id):
    """Удаление объекта"""
    if request.method == 'POST':
        card = Cards.objects.get(pk=id)
        card.delete()
        return HttpResponseRedirect(reverse('cards:index'))


def add_card(request):
    """Добавление нового объекта"""
    if request.method == 'POST':
        form = CardForm(request.POST)
        if form.is_valid():
            new_first_name = form.cleaned_data['first_name']
            new_last_name = form.cleaned_data['last_name']
            new_card_series = form.cleaned_data['card_series']
            new_number_card = form.cleaned_data['number_card']
            new_amount = form.cleaned_data['amount']
            new_data_end = form.cleaned_data['data_end']
            new_status = form.cleaned_data['status']

            new_card = Cards(
                first_name=new_first_name,
                last_name=new_last_name,
                card_series=new_card_series,
                number_card=new_number_card,
                amount=new_amount,
                data_end=new_data_end,
                status=new_status
            )
            new_card.save()
            return render(request, 'cards/add_card.html', {
                'form': CardForm(), 'success': True})
    else:
        form = CardForm()
    return render(request, 'cards/add_card.html', {
        'form': CardForm()})

card_manage/cards/templates/base.html
<!DOCTYPE html> 
<html lang="ru">          
  <head> 
    {% include 'includes/head.html' %} 
    <title>{% block title %}Контент{% endblock title %}</title>      
  </head>
  <body>       
    <header>
    {% include 'includes/header.html' %} 
    </header>
    <main>
      <div class="container py-5">
        {% block content %}
          Контент не подвезли :(
        {% endblock %} 
      </div>
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

card_manage/cards/templates/cards/add_card.html
{% extends 'base.html' %}

{% block content %}
  <h3 class="text-center m-4">Добавить карту</h3>
  {% if success %}
    <div class="alert alert-success" role="alert">
      Новая карта добавлена успешно.
      <a href="{% url 'cards:index' %}" class="alert-link">Перейти на главную страницу.</a>
    </div>
  {% else %}
    <div class="row justify-content-center">
      <div class="col-6">
        <div class="card bg-light mb-3">
          <div class="card-header">
            <i class="fa-solid fa-address-card fa-lg"></i>  Регистрация Карты
          </div>
          <div class="card-body">
            <form action="{% url 'cards:add_card' %}" method="POST">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Добавить</button>
              <a href="{% url 'cards:index' %}" class="btn btn-secondary">Отменить</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

card_manage/cards/templates/cards/edit_card.html
{% extends 'base.html' %}

{% block content %}
  <h3 class="text-center m-4">Редактировать Карту</h3>
  {% if success %}
    <div class="alert alert-success" role="alert">
      Новая карта обнавлена успешно.
      <a href="{% url 'cards:index' %}" class="alert-link">Перейти на главную страницу.</a>
    </div>
  {% else %}
    <div class="row justify-content-center">
      <div class="col-6">
        <div class="card bg-light mb-3">
          <div class="card-header">
            <i class="fa-solid fa-pen-to-square fa-lg"></i> Редактирование Карты
          </div>
          <div class="card-body">
            <form action="" method="POST">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Редактировать</button>
              <a href="{% url 'cards:index' %}" class="btn btn-secondary">Отменить</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

card_manage/cards/templates/cards/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Cards Management System{% endblock %}
{% block content %}
<div class="d-flex flex-columm min-vh-100">
  <div class="container-fluid">
    <h3 class="m-4">Все Карты</h3>
    <div class="row">
      <div class="col-12">
        {% if cards %}

        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4">
            <div class="form-group">
              <input type="text" class="form-control" id="searchField" placeholder="Поиск">
            </div>
          </div>
        </div>
        <p></p>

        <div class="card bg-light ms-4 me-4 mb-4 app-table">
          <div class="card-header"><i class="fa-solid fa-list fa-lg"></i> Список Данных</div>
          <div class="card-body">
            <p class="card-text"></p>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">Имя</th>
                    <th scope="col">Фамилия</th>
                    <th scope="col">Серия карты</th>
                    <th scope="col">Номер карты</th>
                    <th scope="col">Сумма</th>
                    <th scope="col">Дата: с</th>
                    <th scope="col">Дата: до</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Действия</th>
                  </tr>
                </thead>
                <tbody>
                  {% for card in page_obj %}
                  <tr>
                    <td>{{ card.first_name }}</td>
                    <td>{{ card.last_name }}</td>
                    <td>{{ card.card_series }}</td>
                    <td>{{ card.number_card }}</td>
                    <td>{{ card.amount }}</td>
                    <td>{{ card.data_created }}</td>
                    <td>{{ card.data_end }}</td>
                    <td>{{ card.status }}</td>
                    <td>
                      <button type="button" class="btn btn-success me-1" href="{% url 'cards:view_info' card.id %}"
                        data-bs-toggle="modal" data-bs-target="#myModal{{ card.id }}"><i
                          class="fa-solid fa-circle-info"></i>
                      </button>

                      <!--Модальный компонент для Информации Карт-->
                      {% include 'includes/modal_window_info.html' %}

                      <a class="btn btn-warning me-1" href="{% url 'cards:edit_card' card.id %}">
                        <i class="fa-solid fa-pen-to-square"></i>
                      </a>

                      <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                        data-bs-target="#delete_card{{card.id}}">
                        <i class="fa-solid fa-trash-can"></i>
                      </button>

                      <!--Модальный компонент для Удаления Карт-->
                      {% include 'includes/modal_window_delete.html' %}

                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <p class="no-results" style="display: none;">Нет результатов</p>

        <div class="card bg-light ms-4 me-4 mb-4 table-output">
          <div class="card-header"><i class="fa-solid fa-list fa-lg"></i> Результат Поиска</div>
          <div class="card-body">
            <p class="card-text"></p>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">Имя</th>
                    <th scope="col">Фамилия</th>
                    <th scope="col">Серия карты</th>
                    <th scope="col">Номер карты</th>
                    <th scope="col">Сумма</th>
                    <th scope="col">Дата: с</th>
                    <th scope="col">Дата: до</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Действия</th>
                  </tr>
                </thead>
                <tbody class="table-body">

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

      {% else %}
      <h5 class="alert alert-primary ms-4 me-4">В Базе Данных нет Карт</h5>
      {% endif %}

      <!--Пагинатор-->
      {% include 'includes/paginator.html' %}

    </div>
  </div>
</div>
</div>

<script src="{% static 'js/search.js' %}"></script>
{% endblock %}

card_manage/cards/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© Copyright <script>document.write(new Date().getFullYear())</script> <span style="color:red">Card</span>Manager</p>    
</footer>

card_manage/cards/templates/includes/head.html
<meta charset="utf-8"> 
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="msapplication-TileColor" content="#000">
<meta name="theme-color" content="#ffffff">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

card_manage/cards/templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'cards:index' %}"><i class="fa-solid fa-credit-card"></i>  Card Manager</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cards:add_card' %}"><i class="fa-solid fa-plus fa-lg"></i> Добавить Карту</a>
          </li>          
        </ul>        
      </div>
    </div>
  </nav>

card_manage/cards/templates/includes/modal_window_delete.html
<!--Модальный компонент для Удаления Карт-->
                                        
<div class="modal" id="delete_card{{ card.id }}" tabindex="-1" aria-labelledby="myModalLabel2" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Владелец карты: {{ card.first_name }} {{ card.last_name }}</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
          </button>
        </div>
        <div class="modal-body">
          <p>Ты уверен что хочешь удалить эту Карту?</p>
        </div>
        <div class="modal-footer">
          <form action="{% url 'cards:delete_card' card.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Удалить">
          </form>                                                  
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Выйти</button>
        </div>
      </div>
    </div>
  </div>

card_manage/cards/templates/includes/modal_window_info.html
<!--Модальный компонент для Информации Карт-->

<div class="modal" id="myModal{{ card.id }}" tabindex="-1" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Владелец карты: {{ card.first_name }} {{ card.last_name }}</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
          </button>
        </div>
        <div class="modal-body">
          <ul class="list-unstyled">
            <li><strong>{{ card.first_name }} {{ card.last_name }}</strong></li>
            <li>Серия карты: <strong>{{ card.card_series }}</strong></li>
            <li>Номер карты: <strong>{{ card.number_card }}</strong></li>
            <li>Сумма: <strong>{{ card.amount }}</strong></li>
            <li>Дата регистрации: <strong>{{ card.data_created }}</strong></li>
            <li>Дата окончания: <strong>{{ card.data_end }}</strong></li>
            <li>Статус: <strong>{{ card.status }}</strong></li>                                                    
          </ul>
        </div>
        <div class="modal-footer">                                                  
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Выйти</button>
        </div>
      </div>
    </div>
  </div>

card_manage/cards/templates/includes/paginator.html
<!--Пагинатор-->

<div class="pagination-container">
    <div class="">
      Отображаемая страница {{page_obj.number}} из {{ page_obj.paginator.num_pages }}
    </div>

  <ul class="pagination justify-content-end pagination-sm">
    {% if page_obj.has_previous %}
      <li {% if page_obj.number == 1 %} class="page-item active" {% endif %}><a class="page-link" href="?page=1">&laquo; 1</a></li>
      <li class="page-item"> <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущий</a></li>
    {% endif %}

    {% if page_obj.has_next %}
      <li class="page-item"> <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующий</a></li>
      <li class="page-item"> <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages}} &raquo;</a></li>
    {% endif %}  
  </ul>          
  </div>